import type { Metadata } from "next";
import { Pinyon_Script, Poppins, Zalando_Sans } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});
const pinyon = Pinyon_Script({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-pinyon",
});
const zalando = Zalando_Sans({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-zalando",
});

export const metadata: Metadata = {
  title: "Alv Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pinyon.variable} ${zalando.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
