import type { Metadata } from "next";
import {
  DM_Mono,
  Pinyon_Script,
  Poppins,
  Zalando_Sans,
} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Header from "./components/Header";
import { ReactLenis } from "@/lib/lenis";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});
const pinyon = Pinyon_Script({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-pinyon",
});
const zalando = Zalando_Sans({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-zalando",
});
const dmmono = DM_Mono({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-dmmono",
});
// const hatton = Hatton({
//   weight: ["400"],
//   subsets: ["latin"],
//   variable: "--font-hatton",
// });

export const metadata: Metadata = {
  title: "Alv Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body
          className={`${pinyon.variable} ${dmmono.variable} ${zalando.variable} antialiased`}
        >
          <nav>
            <Header />
            <Navbar />
          </nav>
          {children}
        </body>
      </ReactLenis>
    </html>
  );
}
